### PR TITLE
Conference Phases

### PR DESCRIPTION
**Pull request by mtrythall**
Adds support for 3 conference phases: landing, active, archived

* Landing is the pre-conference version of the site, which has limited information. The current PR uses the 2023 content.
* Active is the version of the homepage that provides the full conference experience and content.
* Archived is post-conference, and contains a summary of information. It currently includes placeholders for various pieces of content.

The content for these pages is stored in the `_includes/home` folder.

Phases are controlled by changing values in `_data/site.json`, as documented in the README.md file.

The design of these 3 pages closely mimics their previous versions.

This PR includes other changes:

* Updates documentation to reflect the phase work
* Adds video and slide support to Session pages
* Adds responsive video support for Session pages
* Supports webp for sponsor logos
* Adjusts the Caktus logo to be more readable
* Fixes error where hidden posts would appear in collections
* Alphabetical sorting of presenters
* Support hidden on presenters
* Removes "Talk Outline" from one of the talks in its description as it clashes with on-page headings
* Moves social URLs for DjangoCon US to `site.json`
* Moves social sharing icons for the conference to an include file
* Creates a generic social sharing include file
* Adjusts some grids, and design improvements throughout
* Creates organizers and presenters grid files
* Smaller sizing on sponsor listing images for better balance
* Makes site nav menus wider to avoid some weird wrapping
* Adds an empty avatar image for folks without avatars on the archived page
* Adds initial HTML for future datetime adjustments on schedule
* Adds styleguide file to help Tailwind CSS processing

### CODE REVIEW

**Comment by drewbrew** [comment]
In the case of talks with multiple presenters, the order of speakers is usually relevant: main speaker first and auxiliary ones afterwards, so I'd like to preserve that if possible

**Comment by mtrythall** [comment]
@drewbrew Noted.

Presenter ordering is only impacted when dealing with the generic, full list, as shown on the Archived page.

Screenshot 2024-08-23 at 9 54 10 AM

In the case of showing Presenters on the schedule or on a session page, we follow the ordering in the Markdown file.

I basically updated this code:

```
config.addCollection("presenters", function(collectionApi) {
    return collectionApi.getFilteredByGlob("src/_content/presenters/*.md").sort(function(a, b) {
        let nameA = a.data.name.toUpperCase();
        let nameB = b.data.name.toUpperCase();
        if (nameA < nameB) return -1;
        else if (nameA > nameB) return 1;
        else return 0;
    }).filter(item => !item.data.hidden);
  });
  ```

And that's only called in 1 spot: `presenters-grid.html`

Does that address your concern?

**Comment by mtrythall** [comment]
Additionally, screenshot of my local where presenter ordering is still respected:

Screenshot 2024-08-23 at 9 57 32 AM

**Comment by drewbrew** [comment]
LGTM, thanks! I misread your release notes.

**Comment by mtrythall** [comment]
No, I just didn't specify :) I will fix the conflict soon and merge this later today. Thanks!

**Pull request merged**
